# Generated by Django 4.2 on 2023-04-14 07:21

import django.core.validators
from django.db import migrations, models
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='service')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('massage', tinymce.models.HTMLField(max_length=70)),
                ('massage_1', tinymce.models.HTMLField(validators=[django.core.validators.MinLengthValidator(200)])),
                ('massage_2', tinymce.models.HTMLField(validators=[django.core.validators.MinLengthValidator(200)])),
            ],
        ),
    ]
