# Generated by Django 3.2.12 on 2023-06-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerapply',
            old_name='Career',
            new_name='Careers',
        ),
    ]
