# Generated by Django 3.2.12 on 2023-06-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_career_careerapply_careers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerapply',
            old_name='Careers',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='careerapply',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='careerapply',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='careerapply',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='careerapply',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='careerapply',
            old_name='Qualification',
            new_name='qualification',
        ),
    ]
