# Generated by Django 4.2 on 2023-04-18 08:55

import django.core.validators
from django.db import migrations, models
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_homeproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='career',
            name='email',
        ),
        migrations.RemoveField(
            model_name='career',
            name='message',
        ),
        migrations.RemoveField(
            model_name='career',
            name='name',
        ),
        migrations.RemoveField(
            model_name='career',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='career',
            name='qualification',
        ),
        migrations.AddField(
            model_name='career',
            name='detials',
            field=tinymce.models.HTMLField(default=1, max_length=50, validators=[django.core.validators.MinLengthValidator(70)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='Career'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='teacher',
            field=tinymce.models.HTMLField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeproject',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='HomeProject'),
        ),
    ]
