# Generated by Django 4.2 on 2023-04-18 09:10

import django.core.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_careerapply_remove_career_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='detials',
            field=tinymce.models.HTMLField(max_length=100, validators=[django.core.validators.MinLengthValidator(70)]),
        ),
    ]
