# Generated by Django 3.2.18 on 2023-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_career_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='feature1',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature2',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature3',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature4',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature5',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature6',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature7',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature8',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
