# Generated by Django 3.2.18 on 2023-04-25 05:15

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='home-banner'),
            preserve_default=False,
        ),
    ]
