# Generated by Django 4.2 on 2023-04-27 04:55

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_homebanner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='homesvbaner')),
            ],
        ),
    ]
