# Generated by Django 4.2 on 2023-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_aboutservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutservice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
