# Generated by Django 4.2 on 2023-04-27 05:48

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_aboutservice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Home-project')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='HomeBanner',
            new_name='Banner',
        ),
        migrations.DeleteModel(
            name='HomeProject',
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='home-svc-baner'),
        ),
    ]
