# Generated by Django 4.2 on 2023-04-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_project_rename_homebanner_banner_delete_homeproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutservice',
            name='name',
        ),
    ]
