# Generated by Django 4.2 on 2023-04-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_aboutservice_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutservice',
            new_name='Home_aboutimg',
        ),
    ]
