# Generated by Django 4.2 on 2023-04-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='brand',
            new_name='brand_img',
        ),
    ]
