# Generated by Django 3.2.18 on 2023-05-12 07:08

from django.db import migrations, models
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_brand_delete_brand_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='home-banner')),
                ('career', models.CharField(max_length=500)),
                ('stories', tinymce.models.HTMLField(max_length=700)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='home-svc-baner'),
        ),
    ]
