# Generated by Django 3.2.18 on 2023-05-12 09:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20230512_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='detials_1',
            field=tinymce.models.HTMLField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='detials',
            field=tinymce.models.HTMLField(max_length=100),
        ),
    ]
