# Generated by Django 3.2.18 on 2023-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20230512_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='massage',
            field=models.CharField(max_length=70),
        ),
    ]
