# Generated by Django 3.2.18 on 2023-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_service_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='feature1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='massage',
            field=models.CharField(max_length=70, verbose_name='Service page content'),
        ),
        migrations.AlterField(
            model_name='service',
            name='massage_1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='massage_2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service name'),
        ),
    ]
