# Generated by Django 3.2.18 on 2023-05-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20230512_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='feature1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='massage_1',
            field=models.CharField(max_length=150, null=True, verbose_name='Service more content'),
        ),
        migrations.AlterField(
            model_name='service',
            name='massage_2',
            field=models.CharField(max_length=70, null=True, verbose_name='Service more headline'),
        ),
    ]
