# Generated by Django 3.2.18 on 2023-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20230512_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='feature1',
            field=models.CharField(max_length=200, null=True, verbose_name='Service content 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature2',
            field=models.CharField(max_length=200, null=True, verbose_name='Service content 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature3',
            field=models.CharField(max_length=200, null=True, verbose_name='Service content 3'),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature4',
            field=models.CharField(max_length=200, null=True, verbose_name='Service content 4'),
        ),
    ]
