# Generated by Django 3.2.18 on 2023-05-15 05:14

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20230512_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Blog image', verbose_name='Blog image')),
                ('detials_1', models.CharField(blank=True, max_length=70, null=True, verbose_name='Blog headline')),
                ('detials_2', models.CharField(blank=True, max_length=70, null=True, verbose_name='Blog content')),
                ('detials_3', models.CharField(blank=True, max_length=400, null=True, verbose_name='Blog content')),
                ('detials_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Blog content')),
            ],
            options={
                'verbose_name': 'Add Blog',
                'verbose_name_plural': 'Add Blogs',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='feature5',
            field=models.CharField(max_length=200, null=True, verbose_name='Service content 4'),
        ),
    ]
