# Generated by Django 3.2.18 on 2023-05-18 11:57

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20230515_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_aboutimg',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='home-svc-baner'),
        ),
    ]
