# Generated by Django 3.2.18 on 2023-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_home_aboutimg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_aboutimg',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
