# Generated by Django 3.2.18 on 2023-05-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_home_aboutimg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_aboutimg',
            name='name',
        ),
    ]
