# Generated by Django 3.2.18 on 2023-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20230519_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='career',
            name='detials',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_1',
            field=models.CharField(max_length=200),
        ),
    ]
