# Generated by Django 3.2.18 on 2023-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20230519_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='detials_2',
            field=models.CharField(max_length=200, null=True, verbose_name='Career feature 2'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_3',
            field=models.CharField(max_length=200, null=True, verbose_name='Career feature 3'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_4',
            field=models.CharField(max_length=200, null=True, verbose_name='Career feature 4'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_5',
            field=models.CharField(max_length=200, null=True, verbose_name='Career feature 5'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_6',
            field=models.CharField(max_length=200, null=True, verbose_name='Career feature 6'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_7',
            field=models.CharField(max_length=200, null=True, verbose_name='Career feature 7'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_8',
            field=models.CharField(max_length=200, null=True, verbose_name='Career feature 8'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials',
            field=models.CharField(max_length=200, null=True, verbose_name='Career'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_1',
            field=models.CharField(max_length=200, null=True, verbose_name='Career feature 1'),
        ),
    ]
