# Generated by Django 3.2.18 on 2023-05-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20230519_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='detials',
        ),
        migrations.AddField(
            model_name='career',
            name='Introduction',
            field=models.CharField(max_length=200, null=True, verbose_name='Career Introduction'),
        ),
    ]
