# Generated by Django 3.2.18 on 2023-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20230520_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='Introduction',
            field=models.CharField(max_length=5500, null=True, verbose_name='Career Introduction'),
        ),
    ]
