# Generated by Django 3.2.18 on 2023-05-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_career_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='points_headline',
            field=models.CharField(max_length=100, null=True, verbose_name='points headline'),
        ),
    ]
