# Generated by Django 3.2.18 on 2023-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_career_points_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Career title'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_1',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 1'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_2',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 2'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_3',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 3'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_4',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 4'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_5',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 5'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_6',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 6'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_7',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 7'),
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_8',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 8'),
        ),
        migrations.AlterField(
            model_name='career',
            name='points_headline',
            field=models.CharField(max_length=100, null=True, verbose_name='points headline 1'),
        ),
    ]
