# Generated by Django 3.2.18 on 2023-05-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20230526_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='detials_1',
            new_name='detials_1_1',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='detials_2',
            new_name='detials_1_2',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='detials_3',
            new_name='detials_1_3',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='detials_4',
            new_name='detials_1_4',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='detials_5',
            new_name='detials_1_5',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='detials_6',
            new_name='detials_1_6',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='detials_7',
            new_name='detials_1_7',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='detials_8',
            new_name='detials_1_8',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='points_headline',
            new_name='points_headline_1',
        ),
    ]
