# Generated by Django 3.2.18 on 2023-05-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_auto_20230526_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='detials_2_1',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 1'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_2_2',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 2'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_2_3',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 3'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_2_4',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 4'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_2_5',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 5'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_2_6',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 6'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_2_7',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 7'),
        ),
        migrations.AddField(
            model_name='career',
            name='detials_2_8',
            field=models.CharField(max_length=200, null=True, verbose_name='Career point 8'),
        ),
        migrations.AddField(
            model_name='career',
            name='points_headline_2',
            field=models.CharField(max_length=100, null=True, verbose_name='points headline 1'),
        ),
    ]
