# Generated by Django 3.2.18 on 2023-05-27 10:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_auto_20230527_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='detials_1_1',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
