# Generated by Django 3.2.18 on 2023-05-27 10:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_career_detials_1_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='points_headline_1',
            field=tinymce.models.HTMLField(max_length=100, null=True, verbose_name='points headline 1'),
        ),
    ]
