# Generated by Django 3.2.18 on 2023-05-27 10:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_alter_career_points_headline_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='detials_2_2',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_2_3',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_2_4',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_2_5',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_2_6',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_2_7',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_2_8',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_3_2',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_3_3',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_3_4',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_3_5',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_3_6',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_3_7',
        ),
        migrations.RemoveField(
            model_name='career',
            name='detials_3_8',
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_2_1',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='detials_3_1',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='points_headline_1',
            field=models.CharField(max_length=100, null=True, verbose_name='points headline 1'),
        ),
    ]
