# Generated by Django 3.2.18 on 2023-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_alter_client_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='stories',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='Home-project'),
        ),
    ]
