# Generated by Django 3.2.18 on 2023-05-29 10:00

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20230529_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=700)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='home-banner')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='HomeProject'),
        ),
    ]
