# Generated by Django 3.2.18 on 2023-05-29 11:33

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_auto_20230529_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mobilebanner',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='mobile-banner'),
        ),
    ]
