# Generated by Django 3.2.18 on 2023-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_rename_contactnumber_contactnumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnumber',
            name='footernumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
