# Generated by Django 3.2.12 on 2023-05-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
